#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar  7 19:17:07 2021

@author: Chanmei
"""

infile=open("IMDB-Movie-Data.csv","r",encoding='UTF-8')
data = infile.readlines()

max=0 
for line in data:
      r = line.split("|")
      if float(r[7]) > max:
           max=float(r[7])
print(max)

    

